# Generated by Django 3.0.3 on 2020-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200209_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='Task created 09-02-2020', max_length=256),
        ),
    ]
