# Generated by Django 3.0.3 on 2020-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200209_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
