# Generated by Django 3.0.3 on 2020-02-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_board_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
