# Generated by Django 3.0.3 on 2020-02-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200209_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='Task created 09-02-2020 Feb-02', max_length=256),
        ),
    ]
